// import { IWordItem } from "../type/wordItem";

export const weeks: any = [
  {
    3: [
      [
        { id: 1, word: 'mun', boolean: false, number: '', correct: false },
        { id: 2, word: 'tand', boolean: false, number: '', correct: false },
        { id: 3, word: 'mage', boolean: false, number: '', correct: false },
        { id: 4, word: 'svans', boolean: false, number: '', correct: false },
        { id: 5, word: 'armbåge', boolean: false, number: '', correct: false },
        { id: 6, word: 'axel', boolean: false, number: '', correct: false },
      ],
      [
        { id: 1, word: 'mouth', boolean: false, number: '', correct: false },
        { id: 2, word: 'tooth', boolean: false, number: '', correct: false },
        { id: 3, word: 'stomach', boolean: false, number: '', correct: false },
        { id: 4, word: 'tail', boolean: false, number: '', correct: false },
        { id: 5, word: 'elbow', boolean: false, number: '', correct: false },
        { id: 6, word: 'shoulder', boolean: false, number: '', correct: false },
      ],
    ],
  },
  {
    4: [
      [
        { id: 1, word: 'de', boolean: false, number: '', correct: false },
        { id: 2, word: 'utforska', boolean: false, number: '', correct: false },
        { id: 3, word: 'använda', boolean: false, number: '', correct: false },
        { id: 4, word: 'kikare', boolean: false, number: '', correct: false },
        {
          id: 5,
          word: 'vad gör han?',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 6,
          word: 'självklart',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 7,
          word: 'han håller på att bli galen',
          boolean: false,
          number: '',
          correct: false,
        },
      ],
      [
        { id: 1, word: 'they', boolean: false, number: '', correct: false },
        { id: 2, word: 'explore', boolean: false, number: '', correct: false },
        { id: 3, word: 'use', boolean: false, number: '', correct: false },
        {
          id: 4,
          word: 'binoculars',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 5,
          word: 'what is he doing?',
          boolean: false,
          number: '',
          correct: false,
        },
        { id: 6, word: 'ofcourse', boolean: false, number: '', correct: false },
        {
          id: 7,
          word: 'he is going bananas',
          boolean: false,
          number: '',
          correct: false,
        },
      ],
    ],
  },
  {
    5: [
      [
        {
          id: 1,
          word: 'han skrattar',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 2,
          word: 'han springer runt',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 3,
          word: 'han gör en kullerbytta',
          boolean: false,
          number: '',
          correct: false,
        },
        { id: 4, word: 'floden', boolean: false, number: '', correct: false },
        { id: 5, word: 'retas', boolean: false, number: '', correct: false },
        { id: 6, word: 'fånga', boolean: false, number: '', correct: false },
        { id: 7, word: 'då kom', boolean: false, number: '', correct: false },
      ],
      [
        {
          id: 1,
          word: 'he laughs',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 2,
          word: 'he runs around',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 3,
          word: 'he does a somersault',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 4,
          word: 'the river',
          boolean: false,
          number: '',
          correct: false,
        },
        { id: 5, word: 'teasing', boolean: false, number: '', correct: false },
        { id: 6, word: 'catch', boolean: false, number: '', correct: false },
        {
          id: 7,
          word: 'along came',
          boolean: false,
          number: '',
          correct: false,
        },
      ],
    ],
  },
  {
    6: [
      [
        { id: 1, word: 'hitta', boolean: false, number: '', correct: false },
        { id: 2, word: 'en karta', boolean: false, number: '', correct: false },
        { id: 3, word: 'sten', boolean: false, number: '', correct: false },
        { id: 4, word: 'bredvid', boolean: false, number: '', correct: false },
        {
          id: 5,
          word: 'komma närmare',
          boolean: false,
          number: '',
          correct: false,
        },
        { id: 6, word: 'se upp', boolean: false, number: '', correct: false },
        { id: 7, word: 'skynda', boolean: false, number: '', correct: false },
        { id: 8, word: 'ta', boolean: false, number: '', correct: false },
      ],
      [
        { id: 1, word: 'find', boolean: false, number: '', correct: false },
        { id: 2, word: 'a map', boolean: false, number: '', correct: false },
        { id: 3, word: 'stone', boolean: false, number: '', correct: false },
        { id: 4, word: 'next to', boolean: false, number: '', correct: false },
        {
          id: 5,
          word: 'comes closer',
          boolean: false,
          number: '',
          correct: false,
        },
        {
          id: 6,
          word: 'watch out',
          boolean: false,
          number: '',
          correct: false,
        },
        { id: 7, word: 'hurry up', boolean: false, number: '', correct: false },
        { id: 8, word: 'take', boolean: false, number: '', correct: false },
      ],
    ],
  },
];
